### ISSUE TITLE
Improvements for manga/comics style of text presentation

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#47]
**Describe your idea**
- [x] Allow showing multiple text printers simultaneously
- [x] Allow positioning text printers via naninovel scripts
- [x] Bubble text printer

**Describe possible use cases**
Creating the type of VNs where text is presented in manga/comics manner (eg, inside multiple text boxes/bubbles rather in a single frame).

**Share reference implementations**
![](https://cdn.discordapp.com/attachments/545676116871086083/566789610802380813/shame_shame.png)
https://store.steampowered.com/app/518280/Dead_End_Junction/

**Comment by PeppersGhostSCP** [comment]
Since this is open for discussion I hope you don't mind if I add a couple of suggestions.

> Describe your idea

- Option to bind printer bubble to either background or actor. If actor moves, printer moves with them.
- Separate prefab choice buttons for comic presentation that incorporates choices within printer bubble. (See example.)

> Describe possible use cases
- Freedom of actor movement in the comic presentation would make it more dynamic than a static image. For instance, if an actor appears in the scene with an easing transition, their dialogue bubble will ease in with them instead of popping in separately.  
- Games that use the traditional VA printer could switch to a moving comics presentation as a stylized cutscene. 
- If the game has a heavy comic-style presentation, it would be more immersive if choice options also followed the comic theme. 

> Share reference implementations
An example of printer bubbles **not** syncing with actor appearances in the _Dead End Junction_ trailer (so an example of what could be avoided--notice how the bubbles pop in abruptly):
![Bubbles popping in](https://github.com/PeppersGhostSCP/PeppersStuff/blob/master/DeadEndJunctionPop.gif?raw=true)
Multiple choice bubble from _Night In The Woods_:
![Choice bubble](https://github.com/PeppersGhostSCP/PeppersStuff/blob/master/NightInTheWoodsChooose.gif?raw=true)

**Comment by Elringus** [comment]
Thanks for the suggestions and examples! Not sure if incorporating choices to the printers will work out (though it's definitely worth trying). Looks like an ability to use multiple text printers simultaneously and somehow binding them (both in terms of position and visibility) to characters are essential to this feature.

**Comment by PeppersGhostSCP** [comment]
> Not sure if incorporating choices to the printers will work out (though it's definitely worth trying). 

It does look nice, doesn't it? But if that doesn't work out (or maybe even if it does!) you could also consider an array of choice buttons styled as dialogue bubbles.

It might work as a set of prefab choice buttons (like the map locations) which bind to an actor in the same way as the proposed dialogue bubbles. That would likely operate more similarly to the other systems already in place, while still adhering to the visual theme. 

This is what it looks like in _Oxenfree_:
![Oxenfree choices](https://github.com/PeppersGhostSCP/PeppersStuff/blob/master/OxenfreeChoices.gif?raw=true)

**Comment by Elringus** [comment]
Yeah, that definitively looks nice, though I'm thinking more about functionality, rather then design/looks. I guess the only thing that prevents to create a custom choice handler like that currently is a lack of a (built-in) way to bind its position to a character. And its the same with printers. Guess I'll focus on adding an API and maybe a "non-scripting" way to perform such binding.

**Comment by johnowhetton** [comment]
This is a great idea, from a personal point of view I would love to see a speech bubble style of built in printer, I also feel a thought bubble type of built in printer would be great so you can display thoughts of a particular character

**Comment by Elringus** [comment]
Implemented in `v1.8.0-beta`. 

https://github.com/Elringus/NaninovelWeb/blob/cec01db790eb49fa5d45c2d8ac920f1c40716dc1/docs/guide/text-printers.md#bubble-printer
https://youtu.be/4Z1GkimKQfc
