### ISSUE TITLE
Make the state reset when loading scripts optional

### ISSUE THREAD

**Issue by Alatriste79** [Elringus/NaninovelWeb#65]
When you set a background in one script and you make a "goto" to another script that hasn't set a different background (because I want to keep the previous one), in the new script the background is lost. 

There might be long scenes where the script is split and however both scripts share the same background. If not specified otherwise, the background should be kept.

If this is not possible, at least it would be convenient to check if both backgrounds are the same, and therefore, don't make any background swipe or play any transition unless is specified.

**Comment by Elringus** [comment]
All the engine services are reset when loading another script (which also unloads the backgrounds). Currently it's required because we need to always free the memory before loading a script; this should no longer be the case when context resources management feature (#6) is implemented. I guess we'll add a configuration to select default behavior when loading a new script and a script command to manually unload the resources. I'll change the title to reflect that. 

For the time being, you can assign currently used background appearance to a custom variable and re-use it in the other scripts; to prevent the transition effect, add `time:0` to the `@back` action.

Thanks for the suggestion!

**Comment by Alatriste79** [comment]
Yes, it will be helpful. I found a case where script_1 jumps to Script_2 label, which skips the header part where the background is set. It would be nice to find a way to run mandatory lines of code, so we don't have to repeat them in each label. I'm also thinking it might happen with sounds or other assets that have to be loaded always, no matter what label the goto jumps to.

**Comment by Elringus** [comment]
Implemented in `v1.7.0-beta`. 

![](https://i.gyazo.com/1b1a61b2859341265e1a7e6a1f35bbda.png)
