### ISSUE TITLE
Continue input UI

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#83]
Add a built-in full-screen invisible UI, which should serve as a continue input trigger.

Use case: activating continue input, when the text printers are hidden (eg, during a cutscene or splash/title screens).

**Comment by AriAriAri3** [comment]
Hi - I'd like to add a further suggestion on to this if you don't mind.

When reading visual novels, I'm used to being able to activate continue input no matter where I press on the screen. When I played through your tutorial I was a bit confused when I clicked on the background and nothing happened - it took me a bit of time to realize I had to click on the text printer.

Above you said that the invisible UI would be hidden after it receives a click, but could there be an option to not hide it? Could there be the option to have the invisible UI overlaid on top of the other UIs for the entire duration of the VN (with the exception of choice screens, map screens etc.) so that a reader can click anywhere and have the game progress?

Thank you again :)

**Comment by Elringus** [comment]
While it's possible to set a custom continue input trigger (eg to cover the whole screen), I'm getting quite a lot of questions on this one. Looks like a fullscreen trigger is a more popular solution, after all. I'll think on changing the default trigger so the it'll cover the whole screen in the next update. Thanks for the suggestion!

**Comment by Elringus** [comment]
Implemented in `v1.8.0-beta`. 

Added `IContinueInputUI` — a fullscreen invisible UI layer positioned at the bottom of the UI stack and used to activate a `continue input` trigger when clicked or touched. It's active by default, but can be disabled via naninovel scripts with `@hideUI` and `@showUI` commands (state is saved).
